name: compose-post-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: ComposePostService
  image: deathstarbench/social-network-microservices
  name: compose-post-service
  ports: 
    - containerPort: 9090

  securityContext:
    privileged: true
    capabilities:
      add:
        - "NET_ADMIN"
        - "SYS_RESOURCE"

securityContext:
  sysctls:
    - name: "net.ipv4.tcp_max_syn_backlog"
      value: "65535"
    - name: "net.ipv4.ip_local_port_range"
      value: "1024 65535"
    - name: "net.ipv4.tcp_tw_reuse"
      value: "1"
    - name: "net.ipv4.tcp_fin_timeout"
      value: "10"

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

