name: jaeger

ports:
  - port: 5775
    protocol: UDP
    targetPort: 5775
  - port: 6831
    protocol: UDP
    targetPort: 6831
  - port: 6832
    protocol: UDP
    targetPort: 6832
  - port: 5778
    targetPort: 5778
  - port: 16686
    targetPort: 16686
  - port: 14268
    targetPort: 14268
  - port: 9411
    targetPort: 9411

container:
  env: 
    - name: COLLECTOR_ZIPKIN_HTTP_PORT
      value: "9411"
  image: jaegertracing/all-in-one
  imageVersion: 1.62.0
  name: jaeger
  ports: 
    - containerPort: 5775
      protocol: UDP
    - containerPort: 6831
      protocol: UDP
    - containerPort: 6832
      protocol: UDP
    - containerPort: 5778
    - containerPort: 16686
    - containerPort: 14268
    - containerPort: 9411
  securityContext:
    privileged: true
    capabilities:
      add:
        - "NET_ADMIN"
        - "SYS_RESOURCE"

securityContext:
  sysctls:
    - name: "net.core.somaxconn"
      value: "65535"
    - name: "net.ipv4.tcp_max_syn_backlog"
      value: "65535"
    - name: "net.ipv4.ip_local_port_range"
      value: "1024 65535"
    - name: "net.ipv4.tcp_tw_reuse"
      value: "1"
    - name: "net.ipv4.tcp_fin_timeout"
      value: "10"

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

