apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: sn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
        - name: exporter
          image: nginx/nginx-prometheus-exporter:latest
          args:
            - -nginx.scrape-uri=http://nginx-thrift.sn.svc.cluster.local:8080/status
          ports:
            - containerPort: 9113
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: sn
spec:
  selector:
    app: nginx-exporter
  ports:
    - protocol: TCP
      port: 9113
      targetPort: metrics

