apiVersion: v1
kind: Service
metadata:
  name: nginx-latency-metrics
  namespace: sn
  labels:
    app: nginx-thrift
spec:
  selector:
    app: nginx-thrift
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
