global:
  fqdn_suffix: ".svc.cluster.local" 
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetMemoryUtilizationPercentage: '60'
    targetCPUUtilizationPercentage: '60'
  resources:
    limits:
      cpu: "8"
      memory: 30Gi
    requests:
      cpu: 250m
      memory: 256Mi
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: docker.io
  defaultImageVersion: latest
  redis:
    cluster:
      enabled: false
    standalone:
      enabled: true
    replication:
      primary: redis-master
      replica: redis-replicas
      enabled: false
  memcached:
    cluster:
      enabled: false
      port: &memcached-cluster-port 5000
    standalone:
      enabled: true
  mongodb:
    standalone:
      enabled: true
    sharding:
      enabled: false
      svc:
        name: "mongodb-sharded"
        user: "root"
        password: &mongodb-sharded-password "password"
        port: 27017
  nginx:
    resolverName: kube-dns.kube-system.svc.cluster.local
  jaeger:
    localAgentHostPort: jaeger:6831
    queueSize: 1000000
    bufferFlushInterval: 10
    samplerType: probabilistic
    samplerParam: 0.01
    disabled: false
    logSpans: false
  securityContext:  
    runAsUser: 0
    allowPrivilegeEscalation: true
    capabilities:
      add:
        - "SYS_RESOURCE"  # Allow setting ulimit
    privileged: true
  
  extraConfig:
    sysctls:
      fs.file-max: "2097152"  # Increase max file descriptors
      net.core.somaxconn: "65535"  # Allow high connection backlog
      net.ipv4.tcp_max_syn_backlog: "65535"  # Avoid SYN flood issues
      net.ipv4.ip_local_port_range: "1024 65535"  # Increase available ports
      net.core.rmem_max: "16777216"  # Increase TCP receive buffer
      net.core.wmem_max: "16777216"  # Increase TCP send buffer
      net.core.optmem_max: "16777216"
      net.ipv4.tcp_rmem: "4096 87380 16777216"
      net.ipv4.tcp_wmem: "4096 87380 16777216"
      net.ipv4.tcp_max_tw_buckets: "2000000"  # Increase time-wait buckets
      net.ipv4.tcp_tw_reuse: "1"  # Allow fast reuse of TIME_WAIT sockets
      net.ipv4.tcp_fin_timeout: "10"  # Reduce FIN_WAIT timeout
      net.ipv4.tcp_keepalive_time: "120"
      net.ipv4.tcp_keepalive_intvl: "30"
      net.ipv4.tcp_keepalive_probes: "5"
      net.ipv4.tcp_syncookies: "1"  # Enable SYN cookies to handle DDoS

mongodb-sharded:
  fullnameOverride: mongodb-sharded
  auth:
    rootPassword: *mongodb-sharded-password
  shards: 3
  shardsvr:
    dataNode:
      replicaCount: 3

mcrouter:
  controller: statefulset
  memcached:
    replicaCount: 3
  mcrouterCommandParams.port: *memcached-cluster-port

redis-cluster:
  usePassword: false
  redis:
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false

redis:
  fullnameOverride: "redis"
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false
    replicaCount: 6

